{{- if .Values.nestorService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oat-app.fullname" . }}-cm-nestor
  labels:
    app: {{ include "oat-app.name" . }}
    component: nestor
data:
  env: |
     TZ={{ .Values.nestorService.TZ }}
     DOTENV_FILE={{ .Values.nestorService.DOTENV_FILE }}
     base_path: {{ .Values.nestorService.base_path }} 
{{- end}}