---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ include "oat-app.fullname" . }}-europa
  labels:
    {{- include "oat-app.labels" . | nindent 4 }}
    component: europa
spec:
  type: {{ .Values.europaService.service.type }}
  clusterIP: {{ .Values.europaService.service.clusterIP }}
  ports:
    - port: {{ .Values.europaService.service.port }}
      nodePort: {{ .Values.europaService.service.nodePort }}
      targetPort: {{ .Values.europaService.service.targetPort }}
      protocol: {{ .Values.europaService.service.protocol }}
      name: europa-port
  selector:
    {{- include "oat-app.selectorLabels" . | nindent 4 }}
    component: europa

---