---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ include "oat-app.fullname" . }}-klytie
  labels:
    {{- include "oat-app.labels" . | nindent 4 }}
    component: klytie
spec:
  type: {{ .Values.klytieService.service.type }}
  clusterIP: {{ .Values.klytieService.service.clusterIP }}
  ports:
    - port: {{ .Values.klytieService.service.port }}
      nodePort: {{ .Values.klytieService.service.nodePort }}
      targetPort: {{ .Values.klytieService.service.targetPort }}
      protocol: {{ .Values.klytieService.service.protocol }}
      name: klytie-port
  selector:
    {{- include "oat-app.selectorLabels" . | nindent 4 }}
    component: klytie

---
