---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ include "oat-app.fullname" . }}-lhotse
  labels:
    {{- include "oat-app.labels" . | nindent 4 }}
    component: lhotse
spec:
  type: {{ .Values.lhotseService.service.type }}
  clusterIP: {{ .Values.lhotseService.service.clusterIP }}
  ports:
    - port: {{ .Values.lhotseService.service.port }}
      nodePort: {{ .Values.lhotseService.service.nodePort }}
      targetPort: {{ .Values.lhotseService.service.targetPort }}
      protocol: {{ .Values.lhotseService.service.protocol }}
      name: lhotse-port
  selector:
    {{- include "oat-app.selectorLabels" . | nindent 4 }}
    component: lhotse

---
