---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ include "oat-app.fullname" . }}-nestor
  labels:
    {{- include "oat-app.labels" . | nindent 4 }}
    component: nestor
spec:
  type: {{ .Values.nestorService.service.type }}
  clusterIP: {{ .Values.nestorService.service.clusterIP }}
  ports:
    - port: {{ .Values.nestorService.service.port }}
      nodePort: {{ .Values.nestorService.service.nodePort }}
      targetPort: {{ .Values.nestorService.service.targetPort }}
      protocol: {{ .Values.nestorService.service.protocol }}
      name: nestor-port
  selector:
    {{- include "oat-app.selectorLabels" . | nindent 4 }}
    component: nestor

---
